# Generated by Django 5.0.3 on 2024-04-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('officalemail', models.CharField(max_length=200, unique=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company.department')),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='company.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
