# Generated by Django 5.0.3 on 2024-04-17 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
