# Generated by Django 5.0.3 on 2024-04-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tier',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='company.tier'),
            preserve_default=False,
        ),
    ]
