# Generated by Django 5.0.3 on 2024-04-19 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursementlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200, unique=True)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursementcno', to='company.company')),
            ],
        ),
    ]
