# Generated by Django 5.0.3 on 2024-04-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_reimbursementlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phoneno',
            new_name='gstno',
        ),
    ]
