# Generated by Django 5.0.3 on 2024-04-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_phoneno_company_gstno'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='dno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.department'),
            preserve_default=False,
        ),
    ]
