# Generated by Django 5.0.3 on 2024-04-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_designation_dno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='dno',
        ),
    ]
